### ISSUE TITLE
임시 배포 방법

### ISSUE THREAD

**Issue by kim-kiwon** [kim-kiwon/gogonewyear-be#8]
1. ssh 로 인스턴스 내부로 이동
2. domain-mysql의 application-real.yaml 파일 구성

```yaml
spring:
  datasource:
    url: jdbc:mysql://gogonew-api.capn9lzwwvml.ap-northeast-2.rds.amazonaws.com:3306/gogonew?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
```

3. 빌드 수행
  - `./gradlew clean build :application-external-api:bootJar`

4. 빌드된 결과물로 실행
- `nohup java -jar application-external-api/build/libs/application-external-api-0.0.1.jar --spring.profiles.active=real &`
